version: 0.2 
 
env: 
  variables: 
    CODE_SRC_DIR: "."
    # TF_VERSION: "1.9.3" 
 
phases: 
 
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "yum install -y yum-utils"
      - "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "yum -y install terraform"
  build: 
    commands: 
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "terraform destroy --auto-approve"
      # - "terraform plan"
      # - "terraform apply --auto-approve"
 
  post_build: 
    commands: 
      - echo "deployment complete"