version: 0.2 
 
env: 
  variables: 
    CODE_SRC_DIR: "."
    TF_VERSION: "1.9.3" 
 
phases: 
 
  install: 
    commands: 
      - pwd
      - ls -al
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" 
      - unzip -o terraform.zip 
 
  build: 
    commands: 
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - pwd
      - ls -al
      - terraform -version
      - "terraform init"
      - "terraform plan"
      - "terraform apply"
 
  post_build: 
    commands: 
      - echo "deployment complete"